# -*- encoding : utf-8 -*-
class Monster
  attr_accessor :data

  def initialize
    @data = {
      '0' => {:monsterName => ""},
      '1' => {:monsterName => "莫莉"},
      '2' => {:monsterName => "高級水術士莫莉"},
      '3' => {:monsterName => "水魔法師莫莉"},
      '4' => {:monsterName => "水元素賢者莫莉"},
      '5' => {:monsterName => "肖恩"},
      '6' => {:monsterName => "高級劍士肖恩"},
      '7' => {:monsterName => "火焰劍士肖恩"},
      '8' => {:monsterName => "紅蓮劍士肖恩"},
      '9' => {:monsterName => "鄧肯"},
      '10' => {:monsterName => "牧者鄧肯"},
      '11' => {:monsterName => "德魯依鄧肯"},
      '12' => {:monsterName => "森林王者鄧肯"},
      '13' => {:monsterName => "男爵奈寶尼"},
      '14' => {:monsterName => "子爵奈寶尼"},
      '15' => {:monsterName => "伯爵奈寶尼"},
      '16' => {:monsterName => "侯爵奈寶尼"},
      '17' => {:monsterName => "暗修導士安多"},
      '18' => {:monsterName => "高級暗修導士安多"},
      '19' => {:monsterName => "死靈術士安多"},
      '20' => {:monsterName => "死靈祭師安多"},
      '21' => {:monsterName => "水方士"},
      '22' => {:monsterName => "清川真人"},
      '23' => {:monsterName => "靈江仙人"},
      '24' => {:monsterName => "青龍孟章神君"},
      '25' => {:monsterName => "火方士"},
      '26' => {:monsterName => "赤灶真人"},
      '27' => {:monsterName => "真火仙人"},
      '28' => {:monsterName => "朱雀陵光神君"},
      '29' => {:monsterName => "木方士"},
      '30' => {:monsterName => "九地真人"},
      '31' => {:monsterName => "虛土仙人"},
      '32' => {:monsterName => "玄武執明神君"},
      '33' => {:monsterName => "陽方士"},
      '34' => {:monsterName => "聖明真人"},
      '35' => {:monsterName => "耀尊仙人"},
      '36' => {:monsterName => "白虎監兵神君"},
      '37' => {:monsterName => "陰方士"},
      '38' => {:monsterName => "幽陵真人"},
      '39' => {:monsterName => "紫微妖仙"},
      '40' => {:monsterName => "饕餮渾沌魔君"},
      '41' => {:monsterName => "冰花龍"},
      '42' => {:monsterName => "冰晶龍"},
      '43' => {:monsterName => "冰晶龍王"},
      '44' => {:monsterName => "洋燭龍"},
      '45' => {:monsterName => "星火龍"},
      '46' => {:monsterName => "硝鐵火龍"},
      '47' => {:monsterName => "碧甲龍"},
      '48' => {:monsterName => "碧甲岩龍"},
      '49' => {:monsterName => "靈山龍龜"},
      '50' => {:monsterName => "光輝龍"},
      '51' => {:monsterName => "閃耀龍"},
      '52' => {:monsterName => "聖衡機龍"},
      '53' => {:monsterName => "無頭龍"},
      '54' => {:monsterName => "斷頭龍"},
      '55' => {:monsterName => "魂索邪龍"},
      '56' => {:monsterName => "冰原地精"},
      '57' => {:monsterName => "淵寒大地精"},
      '58' => {:monsterName => "火山地精"},
      '59' => {:monsterName => "熾岩大地精"},
      '60' => {:monsterName => "森林地精"},
      '61' => {:monsterName => "碧石大地精"},
      '62' => {:monsterName => "光明地精"},
      '63' => {:monsterName => "輝芒大地精"},
      '64' => {:monsterName => "黑暗地精"},
      '65' => {:monsterName => "冥土大地精"},
      '66' => {:monsterName => "海精靈"},
      '67' => {:monsterName => "海躍精靈"},
      '68' => {:monsterName => "火精靈"},
      '69' => {:monsterName => "火舞精靈"},
      '70' => {:monsterName => "花精靈"},
      '71' => {:monsterName => "花冠精靈"},
      '72' => {:monsterName => "月精靈"},
      '73' => {:monsterName => "月光精靈"},
      '74' => {:monsterName => "夜精靈"},
      '75' => {:monsterName => "夜迷精靈"},
      '76' => {:monsterName => "冰蜥蜴戰士"},
      '77' => {:monsterName => "冰河蜥蜴戰士"},
      '78' => {:monsterName => "赤蜥蜴戰士"},
      '79' => {:monsterName => "赤焰蜥蜴戰士"},
      '80' => {:monsterName => "翠蜥蜴戰士"},
      '81' => {:monsterName => "森林蜥蜴戰士"},
      '82' => {:monsterName => "光蜥蜴戰士"},
      '83' => {:monsterName => "金光蜥蜴戰士"},
      '84' => {:monsterName => "暗蜥蜴戰士"},
      '85' => {:monsterName => "漆黑蜥蜴戰士"},
      '86' => {:monsterName => "小魔女愛莉絲"},
      '87' => {:monsterName => "占星士愛莉絲"},
      '88' => {:monsterName => "小魔女瑪莉曼"},
      '89' => {:monsterName => "火巫女瑪莉曼"},
      '90' => {:monsterName => "小魔女凱莉絲"},
      '91' => {:monsterName => "修道者凱莉絲"},
      '92' => {:monsterName => "小魔女安迪莉亞"},
      '93' => {:monsterName => "傳教士安迪莉亞"},
      '94' => {:monsterName => "小魔女莉莉絲"},
      '95' => {:monsterName => "鍊金士莉莉絲"},
      '96' => {:monsterName => "水史萊姆"},
      '97' => {:monsterName => "液態史萊姆"},
      '98' => {:monsterName => "火史萊姆"},
      '99' => {:monsterName => "燃燒史萊姆"},
      '100' => {:monsterName => "木史萊姆"},
      '101' => {:monsterName => "翠綠史萊姆"},
      '102' => {:monsterName => "光史萊姆"},
      '103' => {:monsterName => "天使史萊姆"},
      '104' => {:monsterName => "暗史萊姆"},
      '105' => {:monsterName => "幽靈史萊姆"},
      '106' => {:monsterName => "蒼幽狼"},
      '107' => {:monsterName => "蒼幽狼人"},
      '108' => {:monsterName => "赤幽狼"},
      '109' => {:monsterName => "赤幽狼人"},
      '110' => {:monsterName => "青幽狼"},
      '111' => {:monsterName => "青幽狼人"},
      '112' => {:monsterName => "白幽狼"},
      '113' => {:monsterName => "白幽狼人"},
      '114' => {:monsterName => "黑幽狼"},
      '115' => {:monsterName => "黑幽狼人"},
      '116' => {:monsterName => "烏爾德"},
      '117' => {:monsterName => "過去之烏爾德"},
      '118' => {:monsterName => "歷史之烏爾德"},
      '119' => {:monsterName => "斯庫爾德"},
      '120' => {:monsterName => "未來之斯庫爾德"},
      '121' => {:monsterName => "無常之斯庫爾德"},
      '122' => {:monsterName => "薇兒丹蒂"},
      '123' => {:monsterName => "現在之薇兒丹蒂"},
      '124' => {:monsterName => "命運之薇兒丹蒂"},
      '125' => {:monsterName => "伊登"},
      '126' => {:monsterName => "聖果之伊登"},
      '127' => {:monsterName => "永生之伊登"},
      '128' => {:monsterName => "英靈殿侍女"},
      '129' => {:monsterName => "戰魂之瓦爾基麗"},
      '130' => {:monsterName => "催魂之瓦爾基麗"},
      '131' => {:monsterName => "水遊俠"},
      '132' => {:monsterName => "水舞劍士"},
      '133' => {:monsterName => "水舞劍神"},
      '134' => {:monsterName => "火遊俠"},
      '135' => {:monsterName => "火焰戰士"},
      '136' => {:monsterName => "炎舞軍神"},
      '137' => {:monsterName => "木遊俠"},
      '138' => {:monsterName => "翠綠狙擊手"},
      '139' => {:monsterName => "疾風神射手"},
      '140' => {:monsterName => "光遊俠"},
      '141' => {:monsterName => "聖光遊俠"},
      '142' => {:monsterName => "萬劍遊俠"},
      '143' => {:monsterName => "暗遊俠"},
      '144' => {:monsterName => "暗夜刺客"},
      '145' => {:monsterName => "暗影劍豪"},
      '146' => {:monsterName => "冰耀巨像"},
      '147' => {:monsterName => "冰耀巨像 ‧ 解放"},
      '148' => {:monsterName => "冰耀巨鱷"},
      '149' => {:monsterName => "烙紅巨像"},
      '150' => {:monsterName => "烙紅巨像 ‧ 解放"},
      '151' => {:monsterName => "烙紅龍蜥"},
      '152' => {:monsterName => "碧青巨像"},
      '153' => {:monsterName => "碧青巨像 ‧ 解放"},
      '154' => {:monsterName => "碧青行者"},
      '155' => {:monsterName => "聖靈巨像"},
      '156' => {:monsterName => "聖靈巨像 ‧ 解放"},
      '157' => {:monsterName => "聖靈怒獅"},
      '158' => {:monsterName => "暗月巨像"},
      '159' => {:monsterName => "暗月巨像 ‧ 解放"},
      '160' => {:monsterName => "暗月夜龍"},
      '161' => {:monsterName => "機械鯨鯊"},
      '162' => {:monsterName => "強化機械鯨鯊"},
      '163' => {:monsterName => "變異機械鯨鯊"},
      '164' => {:monsterName => "機械獅子"},
      '165' => {:monsterName => "強化機械獅子"},
      '166' => {:monsterName => "狂暴機械獅子"},
      '167' => {:monsterName => "機械犀牛"},
      '168' => {:monsterName => "強化機械犀牛"},
      '169' => {:monsterName => "野蠻機械犀牛"},
      '170' => {:monsterName => "機械狼"},
      '171' => {:monsterName => "強化機械狼"},
      '172' => {:monsterName => "重甲機械狼"},
      '173' => {:monsterName => "機械豹"},
      '174' => {:monsterName => "強化機械豹"},
      '175' => {:monsterName => "掠奪機械豹"},
      '176' => {:monsterName => "海獸"},
      '177' => {:monsterName => "克蘇魯"},
      '178' => {:monsterName => "邪神克蘇魯"},
      '179' => {:monsterName => "地獄三頭犬"},
      '180' => {:monsterName => "基路比魯斯"},
      '181' => {:monsterName => "冥府兇獸基路比魯斯"},
      '182' => {:monsterName => "蛇妖"},
      '183' => {:monsterName => "美杜莎"},
      '184' => {:monsterName => "妖女美杜莎"},
      '185' => {:monsterName => "鷹頭獸"},
      '186' => {:monsterName => "獅鷲"},
      '187' => {:monsterName => "獅鷲獸王"},
      '188' => {:monsterName => "魔羊"},
      '189' => {:monsterName => "魔羊怪"},
      '190' => {:monsterName => "惡魔巴風特"},
      '191' => {:monsterName => "波塞頓"},
      '192' => {:monsterName => "海神波塞頓"},
      '193' => {:monsterName => "赫淮斯托斯"},
      '194' => {:monsterName => "奧林火神赫淮斯托斯"},
      '195' => {:monsterName => "雅典娜"},
      '196' => {:monsterName => "智慧女神雅典娜"},
      '197' => {:monsterName => "阿波羅"},
      '198' => {:monsterName => "光明之神阿波羅"},
      '199' => {:monsterName => "阿提密斯"},
      '200' => {:monsterName => "月之狩獵女神阿提密斯"},
      '201' => {:monsterName => "費雷"},
      '202' => {:monsterName => "勝利海神費雷"},
      '203' => {:monsterName => "提爾"},
      '204' => {:monsterName => "獨臂戰神提爾"},
      '205' => {:monsterName => "費蕾雅"},
      '206' => {:monsterName => "妙曼愛神費蕾雅"},
      '207' => {:monsterName => "索爾"},
      '208' => {:monsterName => "轟天雷神索爾"},
      '209' => {:monsterName => "洛基"},
      '210' => {:monsterName => "黃昏號角洛基"},
      '211' => {:monsterName => "泰芙努特"},
      '212' => {:monsterName => "雨神泰芙努特"},
      '213' => {:monsterName => "賽特"},
      '214' => {:monsterName => "戰爭之神賽特"},
      '215' => {:monsterName => "舒"},
      '216' => {:monsterName => "天空之神 ‧ 舒"},
      '217' => {:monsterName => "拉"},
      '218' => {:monsterName => "太陽之子拉"},
      '219' => {:monsterName => "奧西利斯"},
      '220' => {:monsterName => "不死冥王奧西利斯"},
      '221' => {:monsterName => "海龍"},
      '222' => {:monsterName => "東海龍王 ‧ 敖廣"},
      '223' => {:monsterName => "蓮藕仔"},
      '224' => {:monsterName => "三太子 ‧ 哪吒"},
      '225' => {:monsterName => "大力王"},
      '226' => {:monsterName => "平天大聖 ‧ 牛魔王"},
      '227' => {:monsterName => "美猴王"},
      '228' => {:monsterName => "齊天大聖 ‧ 孫悟空"},
      '229' => {:monsterName => "妖狐"},
      '230' => {:monsterName => "白臉金毛 ‧ 妲己"},
      '231' => {:monsterName => "機械水龍"},
      '232' => {:monsterName => "機械水神龍 ‧ 內拉羅斯"},
      '233' => {:monsterName => "機械火龍"},
      '234' => {:monsterName => "機械火神龍 ‧ 伊索爾德"},
      '235' => {:monsterName => "機械地龍"},
      '236' => {:monsterName => "機械地神龍 ‧ 卡斯迪"},
      '237' => {:monsterName => "機械聖龍"},
      '238' => {:monsterName => "機械聖皇龍 ‧ 泰瑞那斯"},
      '239' => {:monsterName => "機械闇龍"},
      '240' => {:monsterName => "機械冥王龍 ‧ 萊瑞姆"},
      '241' => {:monsterName => "破碎之蒼魂"},
      '242' => {:monsterName => "破碎之赤魂"},
      '243' => {:monsterName => "破碎之青魂"},
      '244' => {:monsterName => "破碎之白魂"},
      '245' => {:monsterName => "破碎之黑魂"},
      '246' => {:monsterName => "重生之蒼魂"},
      '247' => {:monsterName => "重生之赤魂"},
      '248' => {:monsterName => "重生之青魂"},
      '249' => {:monsterName => "重生之白魂"},
      '250' => {:monsterName => "重生之黑魂"},
      '251' => {:monsterName => "共生之蒼魂"},
      '252' => {:monsterName => "共生之赤魂"},
      '253' => {:monsterName => "共生之青魂"},
      '254' => {:monsterName => "共生之白魂"},
      '255' => {:monsterName => "共生之黑魂"},
      '256' => {:monsterName => "永恆之蒼魂"},
      '257' => {:monsterName => "永恆之赤魂"},
      '258' => {:monsterName => "永恆之青魂"},
      '259' => {:monsterName => "永恆之白魂"},
      '260' => {:monsterName => "永恆之黑魂"},
      '261' => {:monsterName => "水晶龍蛋"},
      '262' => {:monsterName => "破殼水晶龍"},
      '263' => {:monsterName => "稀有水晶龍"},
      '264' => {:monsterName => "詛咒之劍"},
      '265' => {:monsterName => "殺戮之劍"},
      '266' => {:monsterName => "魔神之劍"},
      '267' => {:monsterName => "蜜涎獸"},
      '268' => {:monsterName => "蜜羽獸"},
      '269' => {:monsterName => "蜜月獸"},
      '270' => {:monsterName => "海洋小靈魂石"},
      '271' => {:monsterName => "火焰小靈魂石"},
      '272' => {:monsterName => "大地小靈魂石"},
      '273' => {:monsterName => "神聖小靈魂石"},
      '274' => {:monsterName => "鬼魅小靈魂石"},
      '275' => {:monsterName => "海洋靈魂石"},
      '276' => {:monsterName => "火焰靈魂石"},
      '277' => {:monsterName => "大地靈魂石"},
      '278' => {:monsterName => "神聖靈魂石"},
      '279' => {:monsterName => "鬼魅靈魂石"},
      '280' => {:monsterName => "海洋千年靈魂石"},
      '281' => {:monsterName => "火焰千年靈魂石"},
      '282' => {:monsterName => "大地千年靈魂石"},
      '283' => {:monsterName => "神聖千年靈魂石"},
      '284' => {:monsterName => "鬼魅千年靈魂石"},
      '285' => {:monsterName => "元素操縱者 ‧ 迪亞布羅"},
      '286' => {:monsterName => "萬魔之王 ‧ 薩魯曼"},
      '287' => {:monsterName => "碑紋騎士 ‧ 奧丁"},
      '288' => {:monsterName => "雙體共生 ‧ 噬日狼"},
      '289' => {:monsterName => "雙體共生 ‧ ?月狼"},
      '290' => {:monsterName => "雖死猶在 ‧ 毒龍尼德霍格"},
      '291' => {:monsterName => "鬼魅萬年靈魂石"},
      '292' => {:monsterName => "人面怪鳥"},
      '293' => {:monsterName => "米迦勒 ‧ 路西法"},
      '294' => {:monsterName => "通透的蛋"},
      '295' => {:monsterName => "海拉"},
      '296' => {:monsterName => "幻夢魚仙 ‧ 伊德海拉"},
      '297' => {:monsterName => "火紅的蛋"},
      '298' => {:monsterName => "梅格"},
      '299' => {:monsterName => "龍裔 ‧ 梅格蘭斯"},
      '300' => {:monsterName => "翠綠的蛋"},
      '301' => {:monsterName => "伊薇特"},
      '302' => {:monsterName => "蝶妖伊薇特"},
      '303' => {:monsterName => "閃亮的蛋"},
      '304' => {:monsterName => "瑪格"},
      '305' => {:monsterName => "聖蜂后 ‧ 瑪格莉特"},
      '306' => {:monsterName => "暗啞的蛋"},
      '307' => {:monsterName => "伊莎貝爾"},
      '308' => {:monsterName => "黑寡婦伊莎貝爾"},
      '309' => {:monsterName => "水之異界龍"},
      '310' => {:monsterName => "深潛者之父 ‧ 達貢"},
      '311' => {:monsterName => "火之異界龍"},
      '312' => {:monsterName => "火焰共生者 ‧ 克圖格亞"},
      '313' => {:monsterName => "風之異界龍"},
      '314' => {:monsterName => "不朽尖吼者 ‧ 拜亞基"},
      '315' => {:monsterName => "光之異界龍"},
      '316' => {:monsterName => "招蕩的輝芒 ‧ 圖爾茲查"},
      '317' => {:monsterName => "暗之異界龍"},
      '318' => {:monsterName => "群山中之恐怖 ‧ 法格恩"},
      '319' => {:monsterName => "破損的海神守護石像"},
      '320' => {:monsterName => "海神守護石像"},
      '321' => {:monsterName => "破損的火神守護石像"},
      '322' => {:monsterName => "火神守護石像"},
      '323' => {:monsterName => "破損的女戰神守護石像"},
      '324' => {:monsterName => "女戰神守護石像"},
      '325' => {:monsterName => "破損的太陽神守護石像"},
      '326' => {:monsterName => "太陽神守護石像"},
      '327' => {:monsterName => "破損的月神守護石像"},
      '328' => {:monsterName => "月神守護石像"},
      '329' => {:monsterName => "浪濤史萊姆"},
      '330' => {:monsterName => "烈炎史萊姆"},
      '331' => {:monsterName => "花豔史萊姆"},
      '332' => {:monsterName => "神聖史萊姆"},
      '333' => {:monsterName => "邪魔史萊姆"},
      '334' => {:monsterName => "海韻女皇"},
      '335' => {:monsterName => "火岩領主"},
      '336' => {:monsterName => "花冠貴婦"},
      '337' => {:monsterName => "月耀公主"},
      '338' => {:monsterName => "夜影魔女"},
      '339' => {:monsterName => "冰谷蜥蝪騎士"},
      '340' => {:monsterName => "岩漿蜥蝪騎士"},
      '341' => {:monsterName => "密林蜥蝪騎士"},
      '342' => {:monsterName => "聖光蜥蝪騎士"},
      '343' => {:monsterName => "黑雷蜥蝪騎士"},
      '344' => {:monsterName => "特洛伊公主"},
      '345' => {:monsterName => "受詛咒的先知 ‧ 卡珊德拉"},
      '346' => {:monsterName => "科耳喀斯皇女"},
      '347' => {:monsterName => "愛與恨的魔女 ‧ 美狄亞"},
      '348' => {:monsterName => "薩爾瑪提亞女皇"},
      '349' => {:monsterName => "黑魔法女巫 ‧ 喀耳刻"},
      '350' => {:monsterName => "寒霧劍塚 ‧ 卡戎"},
      '351' => {:monsterName => "機關傀儡 ‧ 紅月"},
      '352' => {:monsterName => "腐林魔女 ‧ 布萊爾"},
      '353' => {:monsterName => "鐵處女像 ‧ 浮士德"},
      '354' => {:monsterName => "貓公爵 ‧ 費利克斯"},
      '355' => {:monsterName => "持劍侍女 ‧ 波比"},
      '356' => {:monsterName => "白羊宮 ‧ 波比"},
      '357' => {:monsterName => "攻城者 ‧ 阿姆士唐"},
      '358' => {:monsterName => "金牛宮 ‧ 阿姆士唐"},
      '359' => {:monsterName => "雙劍士 ‧ 波魯克斯"},
      '360' => {:monsterName => "雙子宮 ‧ 加斯陀與波魯克斯"},
      '361' => {:monsterName => "暗影刺客 ‧ 約翰"},
      '362' => {:monsterName => "巨蟹宮 ‧ 約翰"},
      '363' => {:monsterName => "重劍士 ‧ 加里昂"},
      '364' => {:monsterName => "獅子宮 ‧ 加里昂"},
      '365' => {:monsterName => "割穗少女 ‧ 普西芬妮"},
      '366' => {:monsterName => "處女宮 ‧ 普西芬妮"},
      '367' => {:monsterName => "聖殿武士 ‧ 露娜"},
      '368' => {:monsterName => "天秤宮 ‧ 露娜"},
      '369' => {:monsterName => "重鐮刺客 ‧ 艾瑪"},
      '370' => {:monsterName => "天蠍宮 ‧ 艾瑪"},
      '371' => {:monsterName => "綠林行者 ‧ 赫茲"},
      '372' => {:monsterName => "人馬宮 ‧ 赫茲"},
      '373' => {:monsterName => "碎岩武者 ‧ 杜門"},
      '374' => {:monsterName => "山羊宮 ‧ 杜門"},
      '375' => {:monsterName => "鬼魅舞者 ‧ 凱莉"},
      '376' => {:monsterName => "水瓶宮 ‧ 凱莉"},
      '377' => {:monsterName => "海浪騎士 ‧ 卡秋婭與拉?妮斯"},
      '378' => {:monsterName => "雙魚宮 ‧ 卡秋婭與拉?妮斯"},
      '379' => {:monsterName => "黃道星靈 ‧ 水"},
      '380' => {:monsterName => "黃道星靈 ‧ 火"},
      '381' => {:monsterName => "黃道星靈 ‧ 木"},
      '382' => {:monsterName => "黃道星靈 ‧ 光"},
      '383' => {:monsterName => "黃道星靈 ‧ 暗"},
      '384' => {:monsterName => "占星者"},
      '385' => {:monsterName => "見習小丑"},
      '386' => {:monsterName => "無頭小丑"},
      '387' => {:monsterName => "午夜之丑角"},
      '388' => {:monsterName => "不懼的鬼戰士"},
      '389' => {:monsterName => "屠龍者 ‧ 貝奧武夫"},
      '390' => {:monsterName => "不仁的鬼鬥士"},
      '391' => {:monsterName => "戰神 ‧ 阿基里斯"},
      '392' => {:monsterName => "不幸的鬼騎士"},
      '393' => {:monsterName => "薔薇雙槍 ‧ 迪爾姆德"},
      '394' => {:monsterName => "不惑的鬼武士"},
      '395' => {:monsterName => "遮那王 ‧ 源義經"},
      '396' => {:monsterName => "不義的鬼將士"},
      '397' => {:monsterName => "鬼神 ‧ 呂布"},
      '398' => {:monsterName => "光輝萬年靈魂石"},
      '399' => {:monsterName => "暴食史萊姆王"},
      '400' => {:monsterName => "瘋頭"},
      '401' => {:monsterName => "聖言歌姬 ‧ 妍"},
      '402' => {:monsterName => "夜言歌姬 ‧ 希"},
      '403' => {:monsterName => "波拉"},
      '404' => {:monsterName => "奇美拉"},
      '405' => {:monsterName => "潘"},
      '406' => {:monsterName => "福魯斯"},
      '407' => {:monsterName => "拉彌亞"},
      '408' => {:monsterName => "大魔導士莫莉"},
      '409' => {:monsterName => "龍焰騎士肖恩"},
      '410' => {:monsterName => "大地霸主鄧肯"},
      '411' => {:monsterName => "公爵奈寶尼"},
      '412' => {:monsterName => "死靈魔導安多"},
      '413' => {:monsterName => "蒼龍魂使"},
      '414' => {:monsterName => "龍儀姬 ‧ 烏蘇拉"},
      '415' => {:monsterName => "赤龍魂使"},
      '416' => {:monsterName => "龍儀姬 ‧ 愛格德"},
      '417' => {:monsterName => "青龍魂使"},
      '418' => {:monsterName => "龍儀姬 ‧ 芭芭拉"},
      '419' => {:monsterName => "光龍魂使"},
      '420' => {:monsterName => "龍脈者 ‧ 安納"},
      '421' => {:monsterName => "暗龍魂使"},
      '422' => {:monsterName => "龍脈者 ‧ 諾瓦利斯"},
      '423' => {:monsterName => "異域法眼"},
      '424' => {:monsterName => "機關騎士"},
      '425' => {:monsterName => "永劫碑文像"},
      '426' => {:monsterName => "兔魔獸"},
      '427' => {:monsterName => "大耳兔"},
      '428' => {:monsterName => "冒險兔"},
      '429' => {:monsterName => "追憶旅人"},
      '430' => {:monsterName => ""},
      '431' => {:monsterName => "貪婪精靈女王"},
      '432' => {:monsterName => "奪寶海盜"},
      '433' => {:monsterName => "冰晶領航者 ‧ 奪寶海盜"},
      '434' => {:monsterName => "紅纓武者"},
      '435' => {:monsterName => "火靈之舞 ‧ 紅纓武者"},
      '436' => {:monsterName => "捕風酋長"},
      '437' => {:monsterName => "翡翠獵手 ‧ 捕風酋長"},
      '438' => {:monsterName => "清泉守衛"},
      '439' => {:monsterName => "炎鎧戰士"},
      '440' => {:monsterName => "雁目射手"},
      '441' => {:monsterName => "萬劍寵僕"},
      '442' => {:monsterName => "暗影鬥士"},
      '443' => {:monsterName => "占星蛙法師"},
      '444' => {:monsterName => "道法飄蟲"},
      '445' => {:monsterName => "修道雛鴨"},
      '446' => {:monsterName => "賜福蜜蜂"},
      '447' => {:monsterName => "奧秘魚術士"},
      '448' => {:monsterName => "符靈典範 ‧ 綠茵國王"},
      '449' => {:monsterName => "狂怒蜥蜴暴君"},
      '450' => {:monsterName => "法則女神 ‧ 姬氏"},
      '451' => {:monsterName => "地精絞殺者"},
      '452' => {:monsterName => "地精斬首者"},
      '453' => {:monsterName => "地精扼喉者"},
      '454' => {:monsterName => "地精碎骨者"},
      '455' => {:monsterName => "地精切裂者"},
      '456' => {:monsterName => "星佑法師愛莉絲"},
      '457' => {:monsterName => "管狐飼者瑪莉曼"},
      '458' => {:monsterName => "煉屍術士凱莉絲"},
      '459' => {:monsterName => "神罰使者安迪莉亞"},
      '460' => {:monsterName => "鍊金巫師莉莉絲"},
      '461' => {:monsterName => "冽霜武僧"},
      '462' => {:monsterName => "岩焰統領"},
      '463' => {:monsterName => "木靈栽者"},
      '464' => {:monsterName => "聖裁勇者"},
      '465' => {:monsterName => "暗影刺客"},
      '466' => {:monsterName => "貴族伊莉莎白"},
      '467' => {:monsterName => "血浴美人 ‧ 伊莉莎白"},
      '468' => {:monsterName => "信差潔琪"},
      '469' => {:monsterName => "彈簧腿 ‧ 潔琪"},
      '470' => {:monsterName => "婚約者貝莉"},
      '471' => {:monsterName => "罌花新娘 ‧ 貝莉"},
      '472' => {:monsterName => "紳士傑克"},
      '473' => {:monsterName => "開膛怪傑 ‧ 傑克"},
      '474' => {:monsterName => "理髮魔偶陶德"},
      '475' => {:monsterName => "戲謔小丑 ‧ 陶德"},
      '476' => {:monsterName => "冰雪巫師 ‧ 波葛"},
      '477' => {:monsterName => "惡作劇精靈 ‧ 波加特"},
      '478' => {:monsterName => "掃除小精靈 ‧ 布朗尼"},
      '479' => {:monsterName => "沉思的賢者 ‧ 山特古羅斯"},
      '480' => {:monsterName => "色慾胎飼魔母"},
      '481' => {:monsterName => "記憶與遺忘 ‧ 女武神烏爾德"},
      '482' => {:monsterName => "開端與終結 ‧ 女武神斯庫爾德"},
      '483' => {:monsterName => "命定與改變 ‧ 女武神薇兒丹蒂"},
      '484' => {:monsterName => "神木之眷 ‧ 永祭之伊登"},
      '485' => {:monsterName => "破刃之鐮 ‧ 布倫希爾德"},
      '486' => {:monsterName => "水龍牙棋"},
      '487' => {:monsterName => "火龍牙棋"},
      '488' => {:monsterName => "木龍牙棋"},
      '489' => {:monsterName => "光龍牙棋"},
      '490' => {:monsterName => "暗龍牙棋"},
      '491' => {:monsterName => "仰望者瘋帽"},
      '492' => {:monsterName => "狂人三月兔"},
      '493' => {:monsterName => "建言者書頁蟲"},
      '494' => {:monsterName => "餐桌騎士睡鼠"},
      '495' => {:monsterName => "魔郡咧齒貓"},
      '496' => {:monsterName => "魔境之主 紅心女王"},
      '497' => {:monsterName => "笑容守護犬"},
      '498' => {:monsterName => "福德神寵 ‧ 笑犬"},
      '499' => {:monsterName => "怒顏守護犬"},
      '500' => {:monsterName => "懲惡神衛 ‧ 怒犬"},
      '501' => {:monsterName => "韶光仙獸 ‧ 年"}
    }
    @normal_skill = nil
  end

  def parse_normal_skill(data)
    @normal_skill = []
    data.each do |d|
      skill_data = d.split('|')
      skill = {
        :skillId => skill_data[0],
        :minCoolDown => skill_data[1],
        :maxCoolDown => skill_data[2],
        :maxLevel => skill_data[3]
      }
      @normal_skill << skill
    end
  end

  def parse_data(data)
    data.each do |d|
      monster = d.split('|')
      @data[monster[0]][:monsterId] = monster[0]
      @data[monster[0]][:seriesId] = monster[1]
      @data[monster[0]][:levelType] = monster[2]
      @data[monster[0]][:type] = monster[3]
      @data[monster[0]][:attribute] = monster[4]
      @data[monster[0]][:star] = monster[5]
      @data[monster[0]][:rare] = monster[6]
      @data[monster[0]][:size] = monster[7]
      @data[monster[0]][:width] = monster[8]
      @data[monster[0]][:height] = monster[9]
      @data[monster[0]][:maxLevel] = monster[10]
      @data[monster[0]][:expType] = monster[11]
      @data[monster[0]][:attackDuration] = monster[12]
      @data[monster[0]][:leaderSkill] = monster[13]
      @data[monster[0]][:normalSkill] = @normal_skill[monster[14].to_i]
      @data[monster[0]][:baseMergeExp] = monster[15]
      @data[monster[0]][:incMergeExp] = monster[16]
      @data[monster[0]][:baseSellCoin] = monster[17]
      @data[monster[0]][:incSellCoin] = monster[18]
      @data[monster[0]][:baseKillCoin] = monster[19]
      @data[monster[0]][:incKillCoin] = monster[20]
      @data[monster[0]][:baseEvolveCoin] = monster[21]
      @data[monster[0]][:minCardHP] = monster[22]
      @data[monster[0]][:maxCardHP] = monster[23]
      @data[monster[0]][:minCardAttack] = monster[24]
      @data[monster[0]][:maxCardAttack] = monster[25]
      @data[monster[0]][:minCardRecover] = monster[26]
      @data[monster[0]][:maxCardRecover] = monster[27]
      @data[monster[0]][:minEnemyHP] = monster[28]
      @data[monster[0]][:incEnemyHP] = monster[29]
      @data[monster[0]][:minEnemyAttack] = monster[30]
      @data[monster[0]][:incEnemyAttack] = monster[31]
      @data[monster[0]][:minEnemyDefense] = monster[32]
      @data[monster[0]][:incEnemyDefense] = monster[33]
      @data[monster[0]][:evolveMonsterId] = monster[34]
      @data[monster[0]][:evolutionRule0] = monster[35]
      @data[monster[0]][:evolutionRule1] = monster[36]
      @data[monster[0]][:evolutionRule2] = monster[37]
      @data[monster[0]][:evolutionRule3] = monster[38]
      @data[monster[0]][:evolutionRule4] = monster[39]
      @data[monster[0]][:shadowOffsetX] = monster[40]
      @data[monster[0]][:shadowOffsetY] = monster[41]
      @data[monster[0]][:shadowType] = monster[42]
      @data[monster[0]][:groupId] = monster[44]
    end
  end
end
